source_text_prompts = ['a photo of a {}.']
target_text_prompts = [
    'a painting of a {}.',
    'a bad painting of a {}.',
    'a good painting of a {}.',
    'a black and white painting of a {}.',
    'a colorful painting of a {}.',
    'a detailed painting of a {}.',
    'a simple painting of a {}.',
    'a realistic painting of a {}.',
    'an abstract painting of a {}.',
    'a pixelated painting of a {}.',
    'a blurry painting of a {}.',
    'a high resolution painting of a {}.',
    'a low resolution painting of a {}.',
    'a close-up painting of a {}.',
    'a far away painting of a {}.',
    'a large painting of a {}.',
    'a small painting of a {}.',
    'a cartoonish painting of a {}.',
    'a stylized painting of a {}.',
    'an artistic painting of a {}.',
    'a clipart of a {}.',
    'a bad clipart of a {}.',
    'a good clipart of a {}.',
    'a black and white clipart of a {}.',
    'a colorful clipart of a {}.',
    'a detailed clipart of a {}.',
    'a simple clipart of a {}.',
    'a realistic clipart of a {}.',
    'an abstract clipart of a {}.',
    'a pixelated clipart of a {}.',
    'a blurry clipart of a {}.',
    'a high resolution clipart of a {}.',
    'a low resolution clipart of a {}.',
    'a close-up clipart of a {}.',
    'a far away clipart of a {}.',
    'a large clipart of a {}.',
    'a small clipart of a {}.',
    'a cartoonish clipart of a {}.',
    'a stylized clipart of a {}.',
    'an artistic clipart of a {}.',
    'an infographic of a {}.',
    'a bad infographic of a {}.',
    'a good infographic of a {}.',
    'a black and white infographic of a {}.',
    'a colorful infographic of a {}.',
    'a detailed infographic of a {}.',
    'a simple infographic of a {}.',
    'a realistic infographic of a {}.',
    'an abstract infographic of a {}.',
    'a pixelated infographic of a {}.',
    'a blurry infographic of a {}.',
    'a high resolution infographic of a {}.',
    'a low resolution infographic of a {}.',
    'a close-up infographic of a {}.',
    'a far away infographic of a {}.',
    'a large infographic of a {}.',
    'a small infographic of a {}.',
    'a cartoonish infographic of a {}.',
    'a stylized infographic of a {}.',
    'an artistic infographic of a {}.',
    'a quickdraw of a {}.',
    'a bad quickdraw of a {}.',
    'a good quickdraw of a {}.',
    'a black and white quickdraw of a {}.',
    'a colorful quickdraw of a {}.',
    'a detailed quickdraw of a {}.',
    'a simple quickdraw of a {}.',
    'a realistic quickdraw of a {}.',
    'an abstract quickdraw of a {}.',
    'a pixelated quickdraw of a {}.',
    'a blurry quickdraw of a {}.',
    'a high resolution quickdraw of a {}.',
    'a low resolution quickdraw of a {}.',
    'a close-up quickdraw of a {}.',
    'a far away quickdraw of a {}.',
    'a large quickdraw of a {}.',
    'a small quickdraw of a {}.',
    'a cartoonish quickdraw of a {}.',
    'a stylized quickdraw of a {}.',
    'an artistic quickdraw of a {}.',
    'a sketch of a {}.',
    'a bad sketch of a {}.',
    'a good sketch of a {}.',
    'a black and white sketch of a {}.',
    'a colorful sketch of a {}.',
    'a detailed sketch of a {}.',
    'a simple sketch of a {}.',
    'a realistic sketch of a {}.',
    'an abstract sketch of a {}.',
    'a pixelated sketch of a {}.',
    'a blurry sketch of a {}.',
    'a high resolution sketch of a {}.',
    'a low resolution sketch of a {}.',
    'a close-up sketch of a {}.',
    'a far away sketch of a {}.',
    'a large sketch of a {}.',
    'a small sketch of a {}.',
    'a cartoonish sketch of a {}.',
    'a stylized sketch of a {}.',
    'an artistic sketch of a {}.',
    'a real photo of a {}.',
    'a bad real photo of a {}.',
    'a good real photo of a {}.',
    'a black and white real photo of a {}.',
    'a colorful real photo of a {}.',
    'a detailed real photo of a {}.',
    'a simple real photo of a {}.',
    'a realistic real photo of a {}.',
    'an abstract real photo of a {}.',
    'a pixelated real photo of a {}.',
    'a blurry real photo of a {}.',
    'a high resolution real photo of a {}.',
    'a low resolution real photo of a {}.',
    'a close-up real photo of a {}.',
    'a far away real photo of a {}.',
    'a large real photo of a {}.',
    'a small real photo of a {}.',
    'a cartoonish real photo of a {}.',
    'a stylized real photo of a {}.',
    'an artistic real photo of a {}.', '{}',
    'a watercolor of a {}.',
    # 'a 3D model of a {}.',
    'a blueprint of a {}.',
    'a silhouette of a {}.',
    'a vintage photo of a {}.',
    'a futuristic design of a {}.',
    'a mosaic of a {}.',
    'a stained glass of a {}.',
    'a collage of a {}.',
    'a minimalist design of a {}.'
]