source_text_prompts = ['a photo of a {}.']
target_text_prompts = [
    'a painting of a {}.',
    'a clipart of a {}.',
    'a cartoon character of a {}.',
    'an infographic of a {}.',
    'a quickdraw of a {}.',
    'a sketch of a {}.',
    'an advertising posters of a {}.',
    'a sculpture of a {}.',
    'a watercolor of a {}.',
    'a 3D model of a {}.',
    'a blueprint of a {}.',
    'a silhouette of a {}.',
    'a vintage photo of a {}.',
    'a futuristic design of a {}.',
    'a mosaic of a {}.',
    'a stained glass of a {}.',
    'a collage of a {}.',
    'a minimalist design of a {}.',
    'a graffiti of a {}',
    'a virtual reality (VR) environments of a {}',
    'a scientific illustration of a {}',
    'a bad painting of a {}.',
    'a good painting of a {}.',
    'a black and white painting of a {}.',
    'a detailed painting of a {}.',
    'a simple painting of a {}.',
    'a realistic painting of a {}.',
    'an abstract painting of a {}.',
    'a pixelated painting of a {}.',
    'a blurry painting of a {}.',
    'a bad clipart of a {}.',
    'a good clipart of a {}.',
    'a black and white clipart of a {}.',
    'a detailed clipart of a {}.',
    'a simple clipart of a {}.',
    'a realistic clipart of a {}.',
    'an abstract clipart of a {}.',
    'a pixelated clipart of a {}.',
    'a blurry clipart of a {}.',
    'a bad cartoon character of a {}.',
    'a good cartoon character of a {}.',
    'a black and white cartoon character of a {}.',
    'a detailed cartoon character of a {}.',
    'a simple cartoon character of a {}.',
    'a realistic cartoon character of a {}.',
    'an abstract cartoon character of a {}.',
    'a pixelated cartoon character of a {}.',
    'a blurry cartoon character of a {}.',
    'a detailed infographic of a {}.',
    'a simple infographic of a {}.',
    'a colorful infographic of a {}.',
    'a black and white infographic of a {}.',
    'a minimalist infographic of a {}.',
    'a creative infographic of a {}.',
    'a modern infographic of a {}.',
    'a vintage infographic of a {}.',
    'a professional infographic of a {}.',
    'a quickdraw of a {}.',
    'a rough quickdraw of a {}.',
    'a detailed quickdraw of a {}.',
    'a simple quickdraw of a {}.',
    'a messy quickdraw of a {}.',
    'a clean quickdraw of a {}.',
    'a colorful quickdraw of a {}.',
    'a black and white quickdraw of a {}.',
    'a sketchy quickdraw of a {}.',
    'a detailed sketch of a {}.',
    'a rough sketch of a {}.',
    'a simple sketch of a {}.',
    'a colorful sketch of a {}.',
    'a black and white sketch of a {}.',
    'a clean sketch of a {}.',
    'a messy sketch of a {}.',
    'a realistic sketch of a {}.',
    'an abstract sketch of a {}.',
    'a vintage advertising poster of a {}.',
    'a modern advertising poster of a {}.',
    'a colorful advertising poster of a {}.',
    'a black and white advertising poster of a {}.',
    'a minimalist advertising poster of a {}.',
    'a detailed advertising poster of a {}.',
    'a simple advertising poster of a {}.',
    'a large advertising poster of a {}.',
    'a creative advertising poster of a {}.',
    'a marble sculpture of a {}.',
    'a bronze sculpture of a {}.',
    'a wooden sculpture of a {}.',
    'a stone sculpture of a {}.',
    'a metal sculpture of a {}.',
    'a clay sculpture of a {}.',
    'a simple sculpture of a {}.',
    'a modern sculpture of a {}.',
    'a classical sculpture of a {}.',
    'a detailed watercolor of a {}.',
    'a simple watercolor of a {}.',
    'a black and white watercolor of a {}.',
    'a realistic watercolor of a {}.',
    'an abstract watercolor of a {}.',
    'a vibrant watercolor of a {}.',
    'a dull watercolor of a {}.',
    'a large watercolor of a {}.',
    'a small watercolor of a {}.',
    'a detailed 3D model of a {}.',
    'a simple 3D model of a {}.',
    'a colorful 3D model of a {}.',
    'a black and white 3D model of a {}.',
    'a realistic 3D model of a {}.',
    'an abstract 3D model of a {}.',
    'a futuristic 3D model of a {}.',
    'a low-poly 3D model of a {}.',
    'a high-poly 3D model of a {}.',
    'a detailed blueprint of a {}.',
    'a simple blueprint of a {}.',
    'a colorful blueprint of a {}.',
    'a black and white blueprint of a {}.',
    'a realistic blueprint of a {}.',
    'an abstract blueprint of a {}.',
    'a futuristic blueprint of a {}.',
    'a technical blueprint of a {}.',
    'a hand-drawn blueprint of a {}.',
    'a detailed silhouette of a {}.',
    'a simple silhouette of a {}.',
    'a colorful silhouette of a {}.',
    'a black and white silhouette of a {}.',
    'a realistic silhouette of a {}.',
    'an abstract silhouette of a {}.',
    'a futuristic silhouette of a {}.',
    'a classic silhouette of a {}.',
    'a creative silhouette of a {}.',
    'a sepia vintage photo of a {}.',
    'a black and white vintage photo of a {}.',
    'a faded vintage photo of a {}.',
    'a simple vintage photo of a {}.',
    'a realistic vintage photo of a {}.',
    'an abstract vintage photo of a {}.',
    'a colorful vintage photo of a {}.',
    'a small vintage photo of a {}.',
    'a large vintage photo of a {}.',
    'a sleek futuristic design of a {}.',
    'a colorful futuristic design of a {}.',
    'a black and white futuristic design of a {}.',
    'a detailed futuristic design of a {}.',
    'a minimalist futuristic design of a {}.',
    'a complex futuristic design of a {}.',
    'a high-tech futuristic design of a {}.',
    'a low-tech futuristic design of a {}.',
    'a creative futuristic design of a {}.',
    'a simple mosaic of a {}.',
    'a colorful mosaic of a {}.',
    'a black and white mosaic of a {}.',
    'a realistic mosaic of a {}.',
    'an abstract mosaic of a {}.',
    'a large mosaic of a {}.',
    'a small mosaic of a {}.',
    'a vibrant mosaic of a {}.',
    'a dull mosaic of a {}.',
    'a simple stained glass of a {}.',
    'a colorful stained glass of a {}.',
    'a black and white stained glass of a {}.',
    'a realistic stained glass of a {}.',
    'an abstract stained glass of a {}.',
    'a large stained glass of a {}.',
    'a small stained glass of a {}.',
    'a vibrant stained glass of a {}.',
    'a dull stained glass of a {}.',
    'a detailed collage of a {}.',
    'a simple collage of a {}.',
    'a black and white collage of a {}.',
    'a realistic collage of a {}.',
    'an abstract collage of a {}.',
    'a large collage of a {}.',
    'a small collage of a {}.',
    'a vibrant collage of a {}.',
    'a dull collage of a {}.',
    'a colorful minimalist design of a {}.',
    'a black and white minimalist design of a {}.',
    'a detailed minimalist design of a {}.',
    'a simple minimalist design of a {}.',
    'a modern minimalist design of a {}.',
    'a classic minimalist design of a {}.',
    'a creative minimalist design of a {}.',
    'a futuristic minimalist design of a {}.',
    'a clean minimalist design of a {}.',
    'a colorful graffiti of a {}.',
    'a black and white graffiti of a {}.',
    'a detailed graffiti of a {}.',
    'a realistic graffiti of a {}.',
    'an abstract graffiti of a {}.',
    'a large graffiti of a {}.',
    'a small graffiti of a {}.',
    'a vibrant graffiti of a {}.',
    'a dull graffiti of a {}.',
    'a detailed virtual reality (VR) environment of a {}.',
    'a colorful virtual reality (VR) environment of a {}.',
    'a black and white virtual reality (VR) environment of a {}.',
    'a realistic virtual reality (VR) environment of a {}.',
    'an abstract virtual reality (VR) environment of a {}.',
    'a futuristic virtual reality (VR) environment of a {}.',
    'a creative virtual reality (VR) environment of a {}.',
    'a large virtual reality (VR) environment of a {}.',
    'a small virtual reality (VR) environment of a {}.',
    'a detailed scientific illustration of a {}.',
    'a simple scientific illustration of a {}.',
    'a colorful scientific illustration of a {}.',
    'a black and white scientific illustration of a {}.',
    'a realistic scientific illustration of a {}.',
    'an abstract scientific illustration of a {}.',
    'a vintage scientific illustration of a {}.',
    'a large scientific illustration of a {}.',
    'a small scientific illustration of a {}.'
]