source_text_prompts = ['a photo of a {}.']
target_text_prompts = [
    'a painting of a {}.',
    'a clipart illustration of a {}.',
    'an infographic of a {}.',
    'a quickdraw of a {}.',
    'a sketch of a {}.',
    'an advertising posters of a {}.',
    'a sculpture of a {}.',
    'a watercolor of a {}.',
    'a 3D model of a {}.',
    'a blueprint of a {}.',
    'a silhouette of a {}.',
    'a vintage photo of a {}.',
    'a digital art of a {}.',
    'a pencil drawing of a {}.',
    'a technical illustration of a {}.',
    'a doodle of a {}.',
    'a woodcut of a {}.',
    'a lithograph of a {}.',
    'an oil painting of a {}.',
    'a gouache painting of a {}.',
    'an embroidery of a {}.',
    'a charcoal sketch of a {}.',
    'an etching of a {}.',
    'a tattoo design of a {}.',
    'a comic strip of a {}.',
    'a collage of a {}.',
    'a pop art of a {}.',
    'a manga style drawing of a {}.',
    'a minimalist drawing of a {}.',
    'a pixel art of a {}.',
    'a sepia photo of a {}.',
    'a retro style of a {}.',
    'a low-poly model of a {}.',
    'a fantasy art of a {}.',
    'a surrealist painting of a {}.',
    'a futuristic concept art of a {}.',
    'an impressionist painting of a {}.',
    'a hyperrealistic drawing of a {}.',
    'a chalkboard sketch of a {}.',
    'a photo collage of a {}.',
    'a CGI render of a {}.',
    'a stained glass of a {}.',
    'an anime style of a {}.',
    'a Renaissance painting of a {}.',
    'a Victorian engraving of a {}.',
    'a children’s book illustration of a {}.',
    'a pen and ink drawing of a {}.',
    'a crayon drawing of a {}.',
    'a blueprint diagram of a {}.',
    'a steampunk version of a {}.',
    'a street art mural of a {}.',
    'a pastel drawing of a {}.',
    'a scientific diagram of a {}.',
    'a psychedelic art of a {}.',
    'an editorial cartoon of a {}.',
    'a pointillism painting of a {}.',
    'a decorative ornament of a {}.',
    'a folk art version of a {}.',
    'a holographic image of a {}.',
    'a VR model of a {}.',
    'a bronze statue of a {}.',
    'an ancient cave painting of a {}.',
    'a sci-fi style of a {}.',
    'a children coloring book of a {}.',
    'a mixed media art of a {}.',
    'a conceptual sketch of a {}.',
    'a steampunk mechanical drawing of a {}.',
    'a hand-painted mural of a {}.',
    'a pastel artwork of a {}.',
    'an illustrated diagram of a {}.',
    'a vector graphic of a {}.',
    'a medieval manuscript of a {}.',
    'a baroque painting of a {}.',
    'a Cubist painting of a {}.',
    'an Art Deco version of a {}.',
    'an Art Nouveau illustration of a {}.',
    'an acrylic painting of a {}.',
    'a neon sign of a {}.',
    'an icon design of a {}.',
    'a shadow silhouette of a {}.',
    'a cut-paper art of a {}.',
    'a tapestry featuring a {}.',
    'a cross-stitch pattern of a {}.',
    'a visual novel character of a {}.',
    'an emoji of a {}.',
    'a logo of a {}.',
    'a banner featuring a {}.',
    'a motion graphic of a {}.',
    'a kinetic sculpture of a {}.',
    'a vintage postcard of a {}.',
    'a LED display of a {}.',
    'a glass sculpture of a {}.',
    'a sand art representation of a {}.',
    'a flower arrangement resembling a {}.',
    'a fabric pattern of a {}.',
    'an Egyptian hieroglyph of a {}.',
    'a 16-bit video game character of a {}.',
    'a pottery design of a {}.',
    'a metal engraving of a {}.',
    'an origami model of a {}.',
    'a cyberpunk illustration of a {}.',
    'a graffiti stencil of a {}.',
    'a stained glass panel of a {}.',
    'a Rorschach inkblot of a {}.',
    'a Gothic architecture detail of a {}.',
    'a postage stamp of a {}.',
    'a wireframe model of a {}.',
    'a LEGO model of a {}.',
    'a hologram of a {}.',
    'a paper doll of a {}.',
    'a bubble letter graffiti of a {}.',
    'a cookie cutter shape of a {}.',
    'an emoji sticker of a {}.',
    'a flipbook animation of a {}.',
    'a crystal carving of a {}.',
    'a sand sculpture of a {}.',
    'a totem pole with a {}.',
    'a Moai statue resembling a {}.',
    'a scientific model of a {}.',
    'a photo negative of a {}.',
    'a pop-up book with a {}.',
    'a clay sculpture of a {}.',
    'a fabric print of a {}.',
    'a kinetic art piece of a {}.',
    'a chalk pavement art of a {}.',
    'a scrimshaw of a {}.',
    'an augmented reality filter of a {}.',
    'a laser-cut wood model of a {}.',
    'a beadwork pattern of a {}.',
    'a lenticular print of a {}.',
    'a tarot card featuring a {}.',
    'an astrological chart with a {}.',
    'a glass mosaic of a {}.',
    'a domino tile of a {}.',
    'a rubber stamp of a {}.',
    'a fashion illustration of a {}.',
    'a tattoo flash of a {}.',
    'a 2D animation cell of a {}.',
    'a comic book panel of a {}.',
    'a topographic map with a {}.',
    'an ASCII art of a {}.',
    'a street photography shot of a {}.',
    'a stone carving of a {}.',
    'a bookplate illustration of a {}.',
    'a linocut of a {}.',
    'an album cover with a {}.',
    'a silhouette photo of a {}.',
    'a flipbook of a {}.',
    'a watercolor wash of a {}.',
    'a 4-bit pixel icon of a {}.',
    'a map illustration with a {}.',
    'an animated GIF of a {}.',
    'a 3D hologram of a {}.',
    'a typography art of a {}.',
    'a paper cutout of a {}.',
    'a retrowave poster of a {}.',
    'a constellation resembling a {}.',
    'a steampunk icon of a {}.',
    'a painted ceramic tile of a {}.',
    'an abstract representation of a {}.',
    'a shadow puppet of a {}.',
    'a cave engraving of a {}.',
    'a dot matrix print of a {}.',
    'a Rube Goldberg machine featuring a {}.',
    'an aerial view photo of a {}.',
    'an album art design of a {}.',
    'a topographic elevation map of a {}.',
    'a needlepoint design of a {}.',
    'a quilling art piece of a {}.',
    'a badge design of a {}.',
    'a marble statue of a {}.',
    'a glass etching of a {}.',
    'a logo badge of a {}.',
    'a postage stamp illustration of a {}.',
    'an embossed print of a {}.',
    'a neon artwork of a {}.',
    'a street poster with a {}.',
    'an ancient rune of a {}.',
    'a steampunk watch gear featuring a {}.',
    'an environmental infographic of a {}.',
    'a safety sign of a {}.',
    'a blueprint schematic of a {}.',
    'a wire sculpture of a {}.',
    'a papercraft model of a {}.',
    'a photorealistic painting of a {}.',
    'a vintage label of a {}.',
    'a linocut print of a {}.',
    'a painting on driftwood of a {}.',
    'a cave wall painting of a {}.',
    'a tribal tattoo of a {}.',
    'a doodle sticker of a {}.',
    'a video game cover featuring a {}.',
    'an emoji art of a {}.',
    'a lava lamp pattern of a {}.',
    'a comic character of a {}.',
    'a floral arrangement shaped like a {}.',
    'a retro poster of a {}.',
    'a minimalist icon of a {}.',
    'a classic movie poster featuring a {}.',
    'a botanical illustration of a {}.',
    'a cross-sectional diagram of a {}.',
    'a video game avatar of a {}.',
    'a medieval tapestry with a {}.',
    'a carved pumpkin in the shape of a {}.'
]

if __name__ == "__main__":
    import random
    a = [" ".join(prompt.split(" ")[1:-3]) for prompt in target_text_prompts]
    random.shuffle(a[3:])
    tgt_text = ", ".join(a)
    print(0)

